# Setup
title:               Ryan Park
tagline:             'From biometric security to safer airports to COVID-19 therapeutics'
description:         "<a href='https://www.linkedin.com/in/ryan-park-mhs/' target='_blank'>Ryan Park</a>'s AI research portfolio."
url:                 'http://127.0.0.1:4000/' #'https://orangese.github.io/'
baseurl:             ''
paginate:            1
permalink:           pretty
markdown:            kramdown

# About/contact
author:
  name:              Ryan Park
  url:               https://www.linkedin.com/in/ryan-park-mhs/
  email:             ryanpark314@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
